### ISSUE TITLE
Does not launch in VR

### ISSUE THREAD

**Issue by Hoshi82** [cybensis/SPT-VR#10]
I followed the instruction and copied the folders into the main folder. After hitting launch the game window shows up but stays blank and nothing happens until I get "the application isn't responding" and I have to shut down the game.

I removed the dll and the game started just fine. Turned dlss off (thought that might be the issue) and put the dll back in. Now the game loads but still won't go into VR just the flat version.

Closed game, launcher and server and restarted everything. Again game freezes up and won't launch in vr just a blank game window.

Trying to play with the Bigscreen Beyond and Valve Index controller. Since it requires SteamVR I would assume a native SteamVR hmd is supported?

Ok it seems only Meta HMDs are supported atm? Quest 3 worked but sadly not my Beyond.

**Comment by cybensis** [comment]
Thanks for letting me know, when you have the time can you try and run it with the bigscreen beyond again then in your spt folder, go into the BepInEx folder and there should be a log file there, I think it's called LogOutput.log, then share that here. Hopefully that'll give me an idea of what's happening

**Comment by Hoshi82** [comment]
Wanted to record some footage anyway so I will post a pastebin link with the log here. :)

**Comment by Hoshi82** [comment]
Before this thread can be closed, just a question that's not related to the issue, that's not an issue anymore. ^^

Will it be possible to mirror the playermodel for left handed play? Or is it possible at all to put the weapon in the left hand? It's really really hard to aim as a left handed player and even harder in such a "hardcore" game. :)

**Comment by cybensis** [comment]
Glad to hear its working now! And you're in luck, I'm currently working on a left handed mode right now so that'll be available in the next release.
